### ISSUE TITLE
V7: variable fonts and missing characters/ligatures

### ISSUE THREAD

**Issue by subframe7536** [subframe7536/maple-font#151]
- [ ] make it variable with weight and slant axis (temporary) #27
- [ ] some changes on characters
- [ ] complete code range according to `Jetbrains Mono` #139
- [ ] make it as stylesets and provide freezed version #108

[more planned items](https://github.com/users/subframe7536/projects/1)

**Comment by arjpar** [comment]
@subframe7536 When do you think V7 will be released?

**Comment by subframe7536** [comment]
There is no definite time. Probably in the middle of this year.

**Comment by viocha** [comment]
能否考虑支持一下多个等号和多个连字符的连体，下面是cacadia code的样式
![image](https://github.com/subframe7536/maple-font/assets/66580331/7b6f806e-0142-4734-89dd-80fb4241e106)

下面是maple font的现在的样式
![image](https://github.com/subframe7536/maple-font/assets/66580331/8c4cb36a-dd51-43bd-926e-3f55410fa3f8)

**Comment by subframe7536** [comment]
之前也考虑过，但是除了 markdown 表格外，我似乎想不到有什么应用场景

**Comment by viocha** [comment]
> 之前也考虑过，但是除了 markdown 表格外，我似乎想不到有什么应用场景

在注释里面用来分隔不同部分的代码，如果能连在一起，看起来更舒适

**Comment by subframe7536** [comment]
这似乎并不是一个常见的需求。改动起来有些麻烦。我需要考虑一下

**Comment by subframe7536** [comment]
in [monaspace v1.1](https://github.com/githubnext/monaspace/releases/tag/v1.100), they make the decision to break the long sequence equal or hyphen like `----` `====`

**Comment by 0x0-00** [comment]
<img width="315" alt="image" src="https://github.com/subframe7536/maple-font/assets/49114841/ab634359-46f7-4403-9f2a-b38426e97789">
<img width="307" alt="image" src="https://github.com/subframe7536/maple-font/assets/49114841/4025fe20-1b23-4e3a-a1e2-128ca7875ae0">

v7 MapleMono-NF 粗斜体图标显示异常

**Comment by subframe7536** [comment]
@0x0-00 nerd font 升级到v3了

**Comment by subframe7536** [comment]
@0x0-00 regular和bold italic的字符unicode是否一致？

**Comment by subframe7536** [comment]
@0x0-00 粗斜体的字体不是maple mono

**Comment by 0x0-00** [comment]
<img width="377" alt="image" src="https://github.com/subframe7536/maple-font/assets/49114841/836a0055-fe33-44f8-afbc-7fa2e650780f">
<img width="441" alt="image" src="https://github.com/subframe7536/maple-font/assets/49114841/5c5c5456-12c8-47a9-aaa9-a92ca6d874ca">

我设置的是这四种字体

**Comment by subframe7536** [comment]
#198

**Comment by 0x0-00** [comment]
我的字体变体没有问题，只是字体变为粗斜体后nf的图标就跟上图一样出现问题 切换neovim的buffer变为常规字体后 一切恢复正常 我对字体也没有非常深入的了解 不知该如何解决😭

**Comment by mrChest228** [comment]
Please, add oo (infinity) ligature

**Comment by georgealbert** [comment]
请问如何调整行高，字符很漂亮，就是行间距大了，显示的行数有点少。
